version = 1

test_patterns = [
  "**/tests/**",
  "**/test_*.py"
]

exclude_patterns = ["orochi/static/**"]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  skip_doc_coverage = ["module", "magic", "init", "class"]  

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    "compose/local/dask/Dockerfile",
    "compose/local/django/Dockerfile",
    "compose/local/postgres/Dockerfile"
  ]