version: "3"

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  media_path: {}
  data01:
    driver: local

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
      args:
        - http_proxy
        - https_proxy
    image: orochi_local_django
    container_name: orochi_django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app
      - media_path:/media
      - ./symbols/mac:/src/volatility/volatility/symbols/mac
      - ./symbols/linux:/src/volatility/volatility/symbols/linux
      - ./symbols/windows:/src/volatility/volatility/symbols/windows
      - ./symbols/MD5SUMS:/src/volatility/volatility/symbols/MD5SUMS
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
    networks:
      - elastic

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: orochi_production_postgres
    container_name: orochi_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - elastic

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: orochi_mailhog
    ports:
      - "8025:8025"
    networks:
      - elastic

  redis:
    image: redis:6.0.6
    container_name: orochi_redis
    networks:
      - elastic

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
      args:
        - http_proxy
        - https_proxy
    image: orochi_local_node
    container_name: orochi_node
    depends_on:
      - django
    volumes:
      - .:/app
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - "3000:3000"
      # Expose browsersync UI: https://www.browsersync.io/docs/options/#option-ui
      - "3001:3001"
    networks:
      - elastic

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: orochi_es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.9.0
    container_name: orochi_kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic

  scheduler:
    build:
      context: .
      dockerfile: ./compose/local/dask/Dockerfile
      args:
        - http_proxy
        - https_proxy
    image: daskdev/dask
    hostname: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    command: ["dask-scheduler"]
    networks:
      - elastic

  worker01:
    build:
      context: .
      dockerfile: ./compose/local/dask/Dockerfile
      args:
        - http_proxy
        - https_proxy
    image: daskdev/dask
    hostname: dask-worker
    command:
      [
        "dask-worker",
        "--preload",
        "/tmp/daskworkerinit.py",
        "--nthreads",
        "1",
        "--nprocs",
        "2",
        "--memory-limit",
        "3G",
        "tcp://scheduler:8786",
      ]
    volumes:
      - .:/app
      - media_path:/media
      - ./symbols/mac:/src/volatility/volatility/symbols/mac
      - ./symbols/linux:/src/volatility/volatility/symbols/linux
      - ./symbols/windows:/src/volatility/volatility/symbols/windows
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    networks:
      - elastic

  worker02:
    build:
      context: .
      dockerfile: ./compose/local/dask/Dockerfile
      args:
        - http_proxy
        - https_proxy
    image: daskdev/dask
    hostname: dask-worker
    command:
      [
        "dask-worker",
        "--preload",
        "/tmp/daskworkerinit.py",
        "--nthreads",
        "1",
        "--nprocs",
        "2",
        "--memory-limit",
        "3G",
        "tcp://scheduler:8786",
      ]
    volumes:
      - .:/app
      - media_path:/media
      - ./symbols/mac:/src/volatility/volatility/symbols/mac
      - ./symbols/linux:/src/volatility/volatility/symbols/linux
      - ./symbols/windows:/src/volatility/volatility/symbols/windows
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
